version: '3.8'

services:
  order_postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: orderdbusr
      POSTGRES_PASSWORD: orderdbpwd
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  #order_liquibase:
  #  image: liquibase/liquibase:latest
  #  volumes:
  #    - ./order-postgres-db/changelog:/liquibase/changelog
  #    - ./order-postgres-db/changelog/liquibase.log:/liquibase/changelog/liquibase.log
  #    - ./order-postgres-db/changelog/example-changelog.json:/liquibase/changelog/example-changelog.json
  #    - ./order-postgres-db/liquibase.properties:/liquibase/liquibase.properties
  #  depends_on:
  #    - order_postgres_db
  #  entrypoint: ["liquibase"]
  #  command: ["update"]

  order_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    #depends_on:
    #  - order_postgres_db
    #links:
    #  - order_postgres_db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./Presentation/Api/Ecommerce.Order.Presentation.Api/appsettings.json:/app/appsettings.json

volumes:
  postgres-data:
